// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/test.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Action int32

const (
	Action_LOGOUT     Action = 0
	Action_SET_STATUS Action = 1
)

var Action_name = map[int32]string{
	0: "LOGOUT",
	1: "SET_STATUS",
}

var Action_value = map[string]int32{
	"LOGOUT":     0,
	"SET_STATUS": 1,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_938b1d094562548c, []int{0}
}

type ChatMessage struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_938b1d094562548c, []int{0}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type ServerResponse struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerResponse) Reset()         { *m = ServerResponse{} }
func (m *ServerResponse) String() string { return proto.CompactTextString(m) }
func (*ServerResponse) ProtoMessage()    {}
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_938b1d094562548c, []int{1}
}

func (m *ServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerResponse.Unmarshal(m, b)
}
func (m *ServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerResponse.Marshal(b, m, deterministic)
}
func (m *ServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerResponse.Merge(m, src)
}
func (m *ServerResponse) XXX_Size() int {
	return xxx_messageInfo_ServerResponse.Size(m)
}
func (m *ServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerResponse proto.InternalMessageInfo

func (m *ServerResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type ClientRequest struct {
	Action               Action   `protobuf:"varint,1,opt,name=action,proto3,enum=grpc.Action" json:"action,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientRequest) Reset()         { *m = ClientRequest{} }
func (m *ClientRequest) String() string { return proto.CompactTextString(m) }
func (*ClientRequest) ProtoMessage()    {}
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_938b1d094562548c, []int{2}
}

func (m *ClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRequest.Unmarshal(m, b)
}
func (m *ClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRequest.Marshal(b, m, deterministic)
}
func (m *ClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRequest.Merge(m, src)
}
func (m *ClientRequest) XXX_Size() int {
	return xxx_messageInfo_ClientRequest.Size(m)
}
func (m *ClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRequest proto.InternalMessageInfo

func (m *ClientRequest) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_LOGOUT
}

func (m *ClientRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterEnum("grpc.Action", Action_name, Action_value)
	proto.RegisterType((*ChatMessage)(nil), "grpc.ChatMessage")
	proto.RegisterType((*ServerResponse)(nil), "grpc.ServerResponse")
	proto.RegisterType((*ClientRequest)(nil), "grpc.ClientRequest")
}

func init() { proto.RegisterFile("grpc/test.proto", fileDescriptor_938b1d094562548c) }

var fileDescriptor_938b1d094562548c = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0x29, 0x31, 0x35, 0x0e, 0x08, 0xb8, 0x12, 0x42, 0xf0, 0x62, 0x1a, 0x12, 0x09, 0x87,
	0x2d, 0xc1, 0x8b, 0xf1, 0x62, 0xb0, 0x21, 0x5c, 0x24, 0x24, 0x6d, 0xb9, 0x78, 0x31, 0xa5, 0x8e,
	0xb5, 0x0a, 0xbb, 0xb5, 0x3b, 0x35, 0xf1, 0x27, 0xf8, 0xaf, 0x4d, 0xbb, 0x25, 0x4a, 0x0c, 0x7a,
	0xdc, 0xb7, 0x6f, 0xde, 0xbc, 0xf9, 0xa0, 0x19, 0xa5, 0x49, 0x68, 0x13, 0x2a, 0xe2, 0x49, 0x2a,
	0x49, 0xb2, 0x83, 0x5c, 0xe8, 0x9d, 0x45, 0x52, 0x46, 0x6b, 0xb4, 0x0b, 0x6d, 0x95, 0x3d, 0xd9,
	0xb8, 0x49, 0xe8, 0x43, 0x5b, 0xac, 0x0b, 0xa8, 0x39, 0xcf, 0x01, 0xcd, 0x51, 0xa9, 0x20, 0x42,
	0xd6, 0x85, 0xc3, 0x50, 0x0a, 0x42, 0x41, 0x5d, 0xe3, 0xdc, 0x18, 0x1c, 0xb9, 0xdb, 0xa7, 0x35,
	0x84, 0x86, 0x87, 0xe9, 0x3b, 0xa6, 0x2e, 0xaa, 0x44, 0x0a, 0xf5, 0x97, 0x77, 0x01, 0xc7, 0xce,
	0x3a, 0x46, 0x41, 0x2e, 0xbe, 0x65, 0xa8, 0x88, 0xf5, 0xc1, 0x0c, 0x42, 0x8a, 0xa5, 0x28, 0x9c,
	0x8d, 0x71, 0x9d, 0xe7, 0xcd, 0xf8, 0xa4, 0xd0, 0xdc, 0xf2, 0xef, 0x67, 0x60, 0x75, 0x27, 0x70,
	0xd8, 0x07, 0x53, 0x7b, 0x19, 0x80, 0x79, 0xb7, 0x98, 0x2d, 0x96, 0x7e, 0xab, 0xc2, 0x1a, 0x00,
	0xde, 0xd4, 0x7f, 0xf0, 0xfc, 0x89, 0xbf, 0xf4, 0x5a, 0xc6, 0xf8, 0xb3, 0xaa, 0x8f, 0xc9, 0x7b,
	0xc6, 0x21, 0xb2, 0x1b, 0xa8, 0xcf, 0x83, 0x57, 0x2c, 0x4b, 0x28, 0x76, 0xaa, 0xb7, 0xee, 0x54,
	0xeb, 0xb5, 0xb5, 0xb8, 0x7b, 0x9b, 0x55, 0x19, 0x18, 0x23, 0x83, 0x39, 0xd0, 0x74, 0xa4, 0x50,
	0xd9, 0x06, 0x4b, 0x3e, 0x8a, 0x75, 0xb8, 0xa6, 0xc9, 0xb7, 0x34, 0xf9, 0x34, 0xa7, 0xb9, 0x2f,
	0x66, 0x64, 0xb0, 0x2b, 0xa8, 0x79, 0x28, 0x1e, 0xb7, 0x84, 0x4f, 0xca, 0x12, 0xdf, 0xd0, 0xf7,
	0xcd, 0xb2, 0x6b, 0xa8, 0xcd, 0x90, 0xfe, 0x5d, 0xfd, 0x3b, 0xd1, 0xaa, 0xdc, 0x76, 0xee, 0xdb,
	0x2f, 0x99, 0xa2, 0x58, 0x48, 0x1e, 0xca, 0x8d, 0x9d, 0xc8, 0xd0, 0xce, 0x5d, 0x2b, 0xb3, 0x18,
	0xbe, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xa3, 0xd2, 0x60, 0x2c, 0x02, 0x00, 0x00,
}
