// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/test.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Action int32

const (
	Action_LOGOUT     Action = 0
	Action_SET_STATUS Action = 1
)

var Action_name = map[int32]string{
	0: "LOGOUT",
	1: "SET_STATUS",
}

var Action_value = map[string]int32{
	"LOGOUT":     0,
	"SET_STATUS": 1,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_938b1d094562548c, []int{0}
}

type Size int32

const (
	Size_TINY   Size = 0
	Size_SMALL  Size = 1
	Size_MEDIUM Size = 2
	Size_LARGE  Size = 3
	Size_HUGE   Size = 4
)

var Size_name = map[int32]string{
	0: "TINY",
	1: "SMALL",
	2: "MEDIUM",
	3: "LARGE",
	4: "HUGE",
}

var Size_value = map[string]int32{
	"TINY":   0,
	"SMALL":  1,
	"MEDIUM": 2,
	"LARGE":  3,
	"HUGE":   4,
}

func (x Size) String() string {
	return proto.EnumName(Size_name, int32(x))
}

func (Size) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_938b1d094562548c, []int{1}
}

type Payload struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_938b1d094562548c, []int{0}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type PayloadSize struct {
	Size                 Size     `protobuf:"varint,1,opt,name=size,proto3,enum=grpc.Size" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayloadSize) Reset()         { *m = PayloadSize{} }
func (m *PayloadSize) String() string { return proto.CompactTextString(m) }
func (*PayloadSize) ProtoMessage()    {}
func (*PayloadSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_938b1d094562548c, []int{1}
}

func (m *PayloadSize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadSize.Unmarshal(m, b)
}
func (m *PayloadSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadSize.Marshal(b, m, deterministic)
}
func (m *PayloadSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadSize.Merge(m, src)
}
func (m *PayloadSize) XXX_Size() int {
	return xxx_messageInfo_PayloadSize.Size(m)
}
func (m *PayloadSize) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadSize.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadSize proto.InternalMessageInfo

func (m *PayloadSize) GetSize() Size {
	if m != nil {
		return m.Size
	}
	return Size_TINY
}

type ChatMessage struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_938b1d094562548c, []int{2}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type ServerResponse struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerResponse) Reset()         { *m = ServerResponse{} }
func (m *ServerResponse) String() string { return proto.CompactTextString(m) }
func (*ServerResponse) ProtoMessage()    {}
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_938b1d094562548c, []int{3}
}

func (m *ServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerResponse.Unmarshal(m, b)
}
func (m *ServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerResponse.Marshal(b, m, deterministic)
}
func (m *ServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerResponse.Merge(m, src)
}
func (m *ServerResponse) XXX_Size() int {
	return xxx_messageInfo_ServerResponse.Size(m)
}
func (m *ServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerResponse proto.InternalMessageInfo

func (m *ServerResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type ClientRequest struct {
	Action               Action   `protobuf:"varint,1,opt,name=action,proto3,enum=grpc.Action" json:"action,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientRequest) Reset()         { *m = ClientRequest{} }
func (m *ClientRequest) String() string { return proto.CompactTextString(m) }
func (*ClientRequest) ProtoMessage()    {}
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_938b1d094562548c, []int{4}
}

func (m *ClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRequest.Unmarshal(m, b)
}
func (m *ClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRequest.Marshal(b, m, deterministic)
}
func (m *ClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRequest.Merge(m, src)
}
func (m *ClientRequest) XXX_Size() int {
	return xxx_messageInfo_ClientRequest.Size(m)
}
func (m *ClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRequest proto.InternalMessageInfo

func (m *ClientRequest) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_LOGOUT
}

func (m *ClientRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterEnum("grpc.Action", Action_name, Action_value)
	proto.RegisterEnum("grpc.Size", Size_name, Size_value)
	proto.RegisterType((*Payload)(nil), "grpc.Payload")
	proto.RegisterType((*PayloadSize)(nil), "grpc.PayloadSize")
	proto.RegisterType((*ChatMessage)(nil), "grpc.ChatMessage")
	proto.RegisterType((*ServerResponse)(nil), "grpc.ServerResponse")
	proto.RegisterType((*ClientRequest)(nil), "grpc.ClientRequest")
}

func init() { proto.RegisterFile("grpc/test.proto", fileDescriptor_938b1d094562548c) }

var fileDescriptor_938b1d094562548c = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x5f, 0x6b, 0xd4, 0x40,
	0x14, 0xc5, 0x93, 0x35, 0x6e, 0xed, 0xdd, 0x76, 0x1b, 0xc7, 0x52, 0xca, 0x0a, 0x22, 0xb1, 0x60,
	0x59, 0x30, 0x59, 0xea, 0x8b, 0x88, 0x20, 0x6b, 0x0c, 0xb1, 0x90, 0xb8, 0x92, 0x3f, 0x0f, 0xfa,
	0x22, 0x69, 0x7a, 0x8d, 0xd1, 0xdd, 0x99, 0x98, 0x99, 0x08, 0xed, 0x57, 0xf3, 0xcb, 0xc9, 0x24,
	0x13, 0x6c, 0x90, 0x6e, 0x1f, 0xe7, 0xcc, 0x6f, 0xce, 0xfd, 0x73, 0x06, 0x0e, 0x8a, 0xba, 0xca,
	0x1d, 0x81, 0x5c, 0xd8, 0x55, 0xcd, 0x04, 0x23, 0x86, 0x14, 0x66, 0x8f, 0x0b, 0xc6, 0x8a, 0x35,
	0x3a, 0xad, 0x76, 0xd1, 0x7c, 0x73, 0x70, 0x53, 0x89, 0xab, 0x0e, 0xb1, 0x9e, 0xc1, 0xce, 0xa7,
	0xec, 0x6a, 0xcd, 0xb2, 0x4b, 0x72, 0x0c, 0x3b, 0x39, 0xa3, 0x02, 0xa9, 0x38, 0xd6, 0x9f, 0xea,
	0xa7, 0xbb, 0x51, 0x7f, 0xb4, 0x5e, 0xc0, 0x44, 0x41, 0x71, 0x79, 0x8d, 0xe4, 0x09, 0x18, 0xbc,
	0xbc, 0xc6, 0x96, 0x9a, 0x9e, 0x81, 0x2d, 0xab, 0xd8, 0xf2, 0x26, 0x6a, 0x75, 0xeb, 0x39, 0x4c,
	0xdc, 0xef, 0x99, 0x08, 0x91, 0xf3, 0xac, 0xc0, 0x2d, 0xbe, 0x73, 0x98, 0xc6, 0x58, 0xff, 0xc6,
	0x3a, 0x42, 0x5e, 0x31, 0xca, 0xb7, 0xb1, 0x2b, 0xd8, 0x77, 0xd7, 0x25, 0x52, 0x11, 0xe1, 0xaf,
	0x06, 0xb9, 0x20, 0x27, 0x30, 0xce, 0x72, 0x51, 0x32, 0xaa, 0xfa, 0xd8, 0xeb, 0xfa, 0x58, 0xb6,
	0x5a, 0xa4, 0xee, 0x6e, 0x1a, 0x8e, 0x06, 0x86, 0xf3, 0x13, 0x18, 0x77, 0x2c, 0x01, 0x18, 0x07,
	0x2b, 0x7f, 0x95, 0x26, 0xa6, 0x46, 0xa6, 0x00, 0xb1, 0x97, 0x7c, 0x8d, 0x93, 0x65, 0x92, 0xc6,
	0xa6, 0x3e, 0x7f, 0x03, 0x46, 0x3b, 0xf3, 0x03, 0x30, 0x92, 0xf3, 0x8f, 0x9f, 0x4d, 0x8d, 0xec,
	0xc2, 0xfd, 0x38, 0x5c, 0x06, 0x81, 0xa9, 0xcb, 0x87, 0xa1, 0xf7, 0xfe, 0x3c, 0x0d, 0xcd, 0x91,
	0x94, 0x83, 0x65, 0xe4, 0x7b, 0xe6, 0x3d, 0xc9, 0x7e, 0x48, 0x7d, 0xcf, 0x34, 0xce, 0xfe, 0x8c,
	0xba, 0x55, 0xc8, 0x29, 0xcb, 0x1c, 0xc9, 0x5b, 0xd8, 0x0b, 0xb3, 0x9f, 0xa8, 0x46, 0xe0, 0xe4,
	0x51, 0xd7, 0xf3, 0x60, 0xb0, 0xd9, 0xa1, 0x5a, 0xe8, 0x60, 0x33, 0x96, 0x76, 0xaa, 0x2f, 0x74,
	0xe2, 0xc2, 0x81, 0xcb, 0x28, 0x6f, 0x36, 0xa8, 0xb6, 0xcb, 0xc9, 0x91, 0xdd, 0xe5, 0x6b, 0xf7,
	0xf9, 0xda, 0x9e, 0xcc, 0xf7, 0x36, 0x9b, 0x85, 0x4e, 0x5e, 0xc1, 0x24, 0x46, 0x7a, 0xd9, 0xe7,
	0xf3, 0x50, 0x35, 0xf1, 0x2f, 0xb2, 0xdb, 0xde, 0x92, 0xd7, 0x30, 0xf1, 0x51, 0xdc, 0x59, 0xfa,
	0x7f, 0x47, 0x4b, 0x23, 0x0b, 0x00, 0x1f, 0x45, 0xff, 0xd9, 0x14, 0x72, 0xe3, 0x5b, 0xcd, 0xf6,
	0x07, 0x92, 0xa5, 0xbd, 0x3b, 0xfa, 0x72, 0xf8, 0xa3, 0xe1, 0xa2, 0xa4, 0xcc, 0xce, 0xd9, 0xc6,
	0xa9, 0x58, 0xee, 0x48, 0xe2, 0x62, 0xdc, 0x96, 0x7b, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0xbe,
	0x8c, 0xe7, 0x62, 0xf0, 0x02, 0x00, 0x00,
}
